-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 19:50:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema ssafytime
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USER_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USER_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USER_TB` (
  `user_id` VARCHAR(20) NOT NULL,
  `user_pwd` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BOARD_ROOM_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BOARD_ROOM_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BOARD_ROOM_TB` (
  `room_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL,
  `room_name` VARCHAR(300) NOT NULL,
  `register_time` TIMESTAMP NULL DEFAULT now(),
  INDEX `fk_BOARD_ROOM_TB_USER_TB1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`room_no`),
  CONSTRAINT `fk_BOARD_ROOM_TB_USER_TB1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USER_TB` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BOARD_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BOARD_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BOARD_TB` (
  `article_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL,
  `room_no` INT NOT NULL,
  `subject` VARCHAR(100) NULL,
  `content` VARCHAR(2000) NULL,
  `register_time` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`article_no`),
  INDEX `fk_BOARD_TB_USER_TB1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_BOARD_TB_BOARD_ROOM_TB1_idx` (`room_no` ASC) VISIBLE,
  CONSTRAINT `fk_BOARD_TB_USER_TB1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USER_TB` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BOARD_TB_BOARD_ROOM_TB1`
    FOREIGN KEY (`room_no`)
    REFERENCES `mydb`.`BOARD_ROOM_TB` (`room_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BOARD_LIKE_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BOARD_LIKE_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BOARD_LIKE_TB` (
  `like_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL,
  `article_no` INT NOT NULL,
  `register_time` TIMESTAMP NULL DEFAULT now(),
  INDEX `fk_USER_TB_has_BOARD_TB_BOARD_TB1_idx` (`article_no` ASC) VISIBLE,
  INDEX `fk_USER_TB_has_BOARD_TB_USER_TB_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`like_no`),
  CONSTRAINT `fk_USER_TB_has_BOARD_TB_USER_TB`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USER_TB` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_TB_has_BOARD_TB_BOARD_TB1`
    FOREIGN KEY (`article_no`)
    REFERENCES `mydb`.`BOARD_TB` (`article_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REPLY_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`REPLY_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`REPLY_TB` (
  `comment_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL,
  `article_no` INT NOT NULL,
  `register_time` TIMESTAMP NULL DEFAULT now(),
  `comment_content` VARCHAR(1000) NOT NULL,
  INDEX `fk_USER_TB_has_BOARD_TB_BOARD_TB2_idx` (`article_no` ASC) VISIBLE,
  INDEX `fk_USER_TB_has_BOARD_TB_USER_TB1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`comment_no`),
  CONSTRAINT `fk_USER_TB_has_BOARD_TB_USER_TB1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USER_TB` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_TB_has_BOARD_TB_BOARD_TB2`
    FOREIGN KEY (`article_no`)
    REFERENCES `mydb`.`BOARD_TB` (`article_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FILE_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FILE_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FILE_TB` (
  `file_no` INT NOT NULL AUTO_INCREMENT,
  `article_no` INT NOT NULL,
  `save_folder` VARCHAR(45) NOT NULL,
  `original_file` VARCHAR(50) NOT NULL,
  `save_file` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`file_no`),
  INDEX `fk_FILE_TB_BOARD_TB1_idx` (`article_no` ASC) VISIBLE,
  CONSTRAINT `fk_FILE_TB_BOARD_TB1`
    FOREIGN KEY (`article_no`)
    REFERENCES `mydb`.`BOARD_TB` (`article_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MESSAGE_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MESSAGE_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MESSAGE_TB` (
  `message_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL DEFAULT 'set to null',
  `target_id` VARCHAR(20) NULL DEFAULT 'set to null',
  `subject` VARCHAR(100) NOT NULL,
  `content` VARCHAR(2000) NOT NULL,
  `register_time` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`message_no`),
  INDEX `fk_MESSAGE_TB_USER_TB1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_MESSAGE_TB_USER_TB1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USER_TB` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REPLY_BLAME_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`REPLY_BLAME_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`REPLY_BLAME_TB` (
  `blame_no` INT NOT NULL AUTO_INCREMENT,
  `comment_no` INT NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `register_time` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`blame_no`),
  INDEX `fk_REPLY_BLAME_TB_REPLY_TB1_idx` (`comment_no` ASC) VISIBLE,
  CONSTRAINT `fk_REPLY_BLAME_TB_REPLY_TB1`
    FOREIGN KEY (`comment_no`)
    REFERENCES `mydb`.`REPLY_TB` (`comment_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMIN_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ADMIN_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ADMIN_TB` (
  `admin_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`admin_no`),
  INDEX `fk_ADMIN_TB_USER_TB1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_ADMIN_TB_USER_TB1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USER_TB` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BOARD_BLAME_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BOARD_BLAME_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BOARD_BLAME_TB` (
  `blame_no` INT NOT NULL AUTO_INCREMENT,
  `article_no` INT NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `register_time` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`blame_no`),
  INDEX `fk_BOARD_BLAME_TB_BOARD_TB1_idx` (`article_no` ASC) VISIBLE,
  CONSTRAINT `fk_BOARD_BLAME_TB_BOARD_TB1`
    FOREIGN KEY (`article_no`)
    REFERENCES `mydb`.`BOARD_TB` (`article_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BLOCK_TB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BLOCK_TB` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BLOCK_TB` (
  `block_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL,
  `block_id` VARCHAR(20) NULL,
  `register_time` TIMESTAMP NULL DEFAULT now(),
  INDEX `fk_BLOCK_TB_USER_TB1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`block_no`),
  CONSTRAINT `fk_BLOCK_TB_USER_TB1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USER_TB` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
